# Generated by Django 5.1.4 on 2024-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
