# Generated by Django 5.1.4 on 2024-12-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
