# Generated by Django 5.1.4 on 2024-12-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
