# Generated by Django 5.1.4 on 2024-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_customer_email_remove_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('ka', 'kannur'), ('ko', 'kozhikode'), ('kas', 'kasaragod'), ('wa', 'wayanad')], max_length=200),
        ),
    ]
