# Generated by Django 5.1.4 on 2025-01-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_cartitem_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
