# Generated by Django 5.1.4 on 2025-01-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
    ]
