# Generated by Django 5.1.4 on 2025-01-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='order_status',
        ),
    ]
