# Generated by Django 5.1.4 on 2025-01-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_rename_payment_status_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'on the way'), ('Deliverd', 'Deliverd '), ('Cancel', 'Cancel')], default='Placed', max_length=50),
        ),
    ]
