# Generated by Django 5.1.4 on 2025-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Deliverd', 'Deliverd '), ('Cancelled', 'Cancelled')], default='Placed', max_length=50),
        ),
    ]
