# Generated by Django 5.1.4 on 2025-01-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_order_cancellation_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Payment Initiated', 'Payment Initiated')], default='Pending', max_length=100),
        ),
    ]
