# Generated by Django 5.1.4 on 2025-01-22 16:12

from django.db import migrations, models
from django.utils.timezone import now
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
