# Generated by Django 5.1.4 on 2025-01-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_order_order_status_alter_wishlist_created_at'),
    ]

    operations = [
    ]
