# Generated by Django 5.1.4 on 2025-01-23 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('shipped', 'shipped'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Deliverd', 'Deliverd '), ('Cancelled', 'Cancelled')], default='Placed', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
