# Generated by Django 5.1.4 on 2025-01-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
