# Generated by Django 5.1.4 on 2025-01-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnblockRequest',
        ),
    ]
